name: mct_app
description: Migrant Child Tracker MVP
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  uuid: ^3.0.7   # Add this line for Dart 2.19 compatibility

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
